### ISSUE TITLE
Try to use one common node_modules for as many dependencies as possible

### ISSUE THREAD

**Issue by espen42** [enonic/react4xp-npm#45]
Dependabot runs amok on this project because there's one root project and seven subprojects, each with a package.json of their own and a node_modules. Many of the dependencies are the same. Project maintenance will get MUCH easier (and there will be less dependabot noise) if many of the dependencies can use dependencies from one common node_modules at the root.

**Comment by espen42** [comment]
Builds, but mocha fails at testing:

```
>  mocha --require @babel/register --require @babel/polyfill --require packages/buildcomponents/test/test_helper.js "packages/buildcomponents/test/**/*@(spec.js)"
/Users/espenjobb/source/_npm_libs/react4xp-mono/packages/buildcomponents/test/build_entries_and_chunks_spec.js:1
import { expect } from 'chai';
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at wrapSafe (internal/modules/cjs/loader.js:915:16)
    at Module._compile (internal/modules/cjs/loader.js:963:27)
    at Module._compile (/Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.newLoader [as .js] (/Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at /Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/mocha/lib/mocha.js:250:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/mocha/lib/mocha.js:247:14)
    at Mocha.run (/Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/mocha/lib/mocha.js:576:10)
    at Object.<anonymous> (/Users/espenjobb/source/_npm_libs/react4xp-mono/node_modules/mocha/bin/_mocha:637:18)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

```
