### ISSUE TITLE
Can't publish react4xp-buildconstants@1.0.0

### ISSUE THREAD

**Issue by espen42** [enonic/react4xp-npm#5]
`npm publish --dry-run` completes successfully, but `npm publish`yields:

```
>  npm publish          
npm notice 
npm notice 📦  react4xp-buildconstants@1.0.0
npm notice === Tarball Contents === 
npm notice 11.4kB LICENSE                  
npm notice 421B   bin/cli.js               
npm notice 941B   ensureTargetOutputPath.js
npm notice 7.1kB  index.js                 
npm notice 2.1kB  package.json             
npm notice 570B   CHANGELOG.md             
npm notice 7.3kB  README.md                
npm notice === Tarball Details === 
npm notice name:          react4xp-buildconstants                 
npm notice version:       1.0.0                                   
npm notice package size:  10.1 kB                                 
npm notice unpacked size: 29.8 kB                                 
npm notice shasum:        05b4a6a85ce9f3e2c3228f11b53d6f47b60f78e6
npm notice integrity:     sha512-mgmfgRYo1Xoz+[...]fc4fbv+WHg9zw==
npm notice total files:   7                                       
npm notice 
npm ERR! code E400
npm ERR! 400 Bad Request - PUT https://registry.npmjs.org/react4xp-buildconstants - deprecations must be strings

npm ERR! A complete log of this run can be found in:
npm ERR!     (...)npm/_logs/2020-06-19T13_08_18_270Z-debug.log
```

2020-06-19T13_08_18_270Z-debug.log:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/espenjobb/.nvm/versions/node/v9.7.0/bin/node',
1 verbose cli   '/Users/espenjobb/.nvm/versions/node/v9.7.0/bin/npm',
1 verbose cli   'publish' ]
2 info using npm@6.12.0
3 info using node@v9.7.0
4 verbose npm-session eaed94e68036e7d8
5 verbose publish [ '.' ]
6 info lifecycle react4xp-buildconstants@1.0.0~prepublish: react4xp-buildconstants@1.0.0
7 info lifecycle react4xp-buildconstants@1.0.0~prepare: react4xp-buildconstants@1.0.0
8 info lifecycle react4xp-buildconstants@1.0.0~prepublishOnly: react4xp-buildconstants@1.0.0
9 info lifecycle react4xp-buildconstants@1.0.0~prepack: react4xp-buildconstants@1.0.0
10 info lifecycle react4xp-buildconstants@1.0.0~postpack: react4xp-buildconstants@1.0.0
11 notice
12 notice 📦  react4xp-buildconstants@1.0.0
13 notice === Tarball Contents ===
14 notice 11.4kB LICENSE
14 notice 421B   bin/cli.js
14 notice 941B   ensureTargetOutputPath.js
14 notice 7.1kB  index.js
14 notice 2.1kB  package.json
14 notice 570B   CHANGELOG.md
14 notice 7.3kB  README.md
15 notice === Tarball Details ===
16 notice name:          react4xp-buildconstants
16 notice version:       1.0.0
16 notice package size:  10.1 kB
16 notice unpacked size: 29.8 kB
16 notice shasum:        05b4a6a85ce9f3e2c3228f11b53d6f47b60f78e6
16 notice integrity:     sha512-mgmfgRYo1Xoz+[...]fc4fbv+WHg9zw==
16 notice total files:   7
17 notice
18 http fetch PUT 400 https://registry.npmjs.org/react4xp-buildconstants 1327ms
19 verbose stack Error: 400 Bad Request - PUT https://registry.npmjs.org/react4xp-buildconstants - deprecations must be strings
19 verbose stack     at res.buffer.catch.then.body (/Users/espenjobb/.nvm/versions/node/v9.7.0/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:104:15)
19 verbose stack     at <anonymous>
19 verbose stack     at process._tickCallback (internal/process/next_tick.js:118:7)
20 verbose statusCode 400
21 verbose pkgid react4xp-buildconstants@1.0.0
22 verbose cwd /Users/espenjobb/source/_npm_libs/react4xp-mono/packages/constants
23 verbose Darwin 19.4.0
24 verbose argv "/Users/espenjobb/.nvm/versions/node/v9.7.0/bin/node" "/Users/espenjobb/.nvm/versions/node/v9.7.0/bin/npm" "publish"
25 verbose node v9.7.0
26 verbose npm  v6.12.0
27 error code E400
28 error 400 Bad Request - PUT https://registry.npmjs.org/react4xp-buildconstants - deprecations must be strings
29 verbose exit [ 1, true ]
```

**Comment by espen42** [comment]
This is not really a blocker, since it's currently only the version that's changed. Releasing react4xp@1.0.0 to NPM is probably okay with a beta-looking version for the _react4xp-buildconstants_ subpackage.

But it might be tricky to solve - only one actual help link found so far (https://stackoverflow.com/questions/49255835/deprecations-must-be-strings-error-when-publishing-package-to-npm/49255850#49255850) but that solution didn't help at all. 

Hopefully this won't be a problem for future upgrades.

**Comment by espen42** [comment]
Due to higher deprecated versions released years ago at npmjs.org. Jumped version of this package to 4.x.x, fixed it. Current version is 4.0.2.
